classdef getCwhLtiSystemTest < matlab.unittest.TestCase

    methods (Test)

        function testIncorrectInvalidInputSpace(testCase)
            GaussianDist = RandomVector('Gaussian', ...
                 zeros(4,1), ...
                 diag([1e-4, 1e-4, 5e-8, 5e-8]));
            testCase.verifyError(@() getCwhLtiSystem(4, ... 
                 'wer', GaussianDist), 'SReachTools:invalidArgs');
        end        
        
        function testIncorrectInvalidDimInputPolyhedron(testCase)
            GaussianDist = RandomVector('Gaussian', ...
                 zeros(4,1), ...
                 diag([1e-4, 1e-4, 5e-8, 5e-8]));
            testCase.verifyError(@() getCwhLtiSystem(4, ... 
                 Polyhedron('lb', -0.01*ones(3,1), ...
                            'ub',  0.01*ones(3,1)), ...
                 GaussianDist), 'SReachTools:invalidArgs');
        end
        
        function testIncorrectGaussian(testCase)
            inputSpace = Polyhedron('lb', -0.01*ones(2,1), ...
                 'ub',  0.01*ones(2,1));                                 
            GaussianDist = RandomVector('Gaussian', ...
                 zeros(2,1), ...
                 diag([1e-4, 1e-4]));
            testCase.verifyError(@() getCwhLtiSystem(4, ... 
                 inputSpace, ...
                 GaussianDist), 'SReachTools:invalidArgs');
        end          

        function testCorrect4DCwh(testCase)
            inputSpace = Polyhedron('lb', -0.01*ones(2,1), ...
                 'ub',  0.01*ones(2,1));                                 
            GaussianDist = RandomVector('Gaussian', ...
                 zeros(4,1), ...
                 diag([1e-4, 1e-4, 5e-8, 5e-8]));
            testCase.verifyClass(getCwhLtiSystem(4, ... 
                 inputSpace, ...
                 GaussianDist), 'LtiSystem');
        end
                
    end
end